/**
 * Custom Worker entry: `/ws` is handled by the RoomObject Durable Object,
 * everything else goes to the OpenNext-built Next.js handler.
 */
// @ts-expect-error — generated by `opennextjs-cloudflare build`
import nextApp from "../.open-next/worker.js";
import { RoomObject, type Env } from "./room-object";

export { RoomObject };

const ROOM_CODE = /^[A-Z0-9]{6}$/;

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/ws") {
      const code = (url.searchParams.get("room") ?? "").toUpperCase();
      if (!ROOM_CODE.test(code)) return new Response("Invalid room code", { status: 400 });
      const id = env.ROOMS.idFromName(code);
      return env.ROOMS.get(id).fetch(request);
    }
    return (nextApp as { fetch: (r: Request, e: Env, c: ExecutionContext) => Promise<Response> }).fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;
